// Generated by https://quicktype.io

export interface Pokemon {
  // eslint-disable-next-line no-use-before-define
  abilities: Ability[];
  base_experience: number;
  // eslint-disable-next-line no-use-before-define
  forms: Species[];
  // eslint-disable-next-line no-use-before-define
  game_indices: GameIndex[];
  height: number;
  held_items: any[];
  id: number;
  is_default: boolean;
  location_area_encounters: string;
  // eslint-disable-next-line no-use-before-define
  moves: Move[];
  name: string;
  order: number;
  past_types: any[];
  // eslint-disable-next-line no-use-before-define
  species: Species;
  // eslint-disable-next-line no-use-before-define
  sprites: Sprites;
  // eslint-disable-next-line no-use-before-define
  stats: Stat[];
  // eslint-disable-next-line no-use-before-define
  types: Type[];
  weight: number;
}

export interface Ability {
  // eslint-disable-next-line no-use-before-define
  ability: Species;
  is_hidden: boolean;
  slot: number;
}

export interface Species {
  name: string;
  url: string;
}

export interface GameIndex {
  game_index: number;
  version: Species;
}

export interface Move {
  move: Species;
  // eslint-disable-next-line no-use-before-define
  version_group_details: VersionGroupDetail[];
}

export interface VersionGroupDetail {
  level_learned_at: number;
  move_learn_method: Species;
  version_group: Species;
}

export interface GenerationV {
  // eslint-disable-next-line no-use-before-define
  'black-white': Sprites;
}

export interface GenerationIv {
  // eslint-disable-next-line no-use-before-define
  'diamond-pearl': Sprites;
  // eslint-disable-next-line no-use-before-define
  'heartgold-soulsilver': Sprites;
  // eslint-disable-next-line no-use-before-define
  platinum: Sprites;
}

export interface Versions {
  // eslint-disable-next-line no-use-before-define
  'generation-i': GenerationI;
  // eslint-disable-next-line no-use-before-define
  'generation-ii': GenerationIi;
  // eslint-disable-next-line no-use-before-define
  'generation-iii': GenerationIii;
  'generation-iv': GenerationIv;
  'generation-v': GenerationV;
  // eslint-disable-next-line no-use-before-define
  'generation-vi': { [key: string]: Home };
  // eslint-disable-next-line no-use-before-define
  'generation-vii': GenerationVii;
  // eslint-disable-next-line no-use-before-define
  'generation-viii': GenerationViii;
}

export interface Sprites {
  back_default: string;
  back_female: null;
  back_shiny: string;
  back_shiny_female: null;
  front_default: string;
  front_female: null;
  front_shiny: string;
  front_shiny_female: null;
  // eslint-disable-next-line no-use-before-define
  other?: Other;
  versions?: Versions;
  animated?: Sprites;
}

export interface GenerationI {
  // eslint-disable-next-line no-use-before-define
  'red-blue': RedBlue;
  // eslint-disable-next-line no-use-before-define
  yellow: RedBlue;
}

export interface RedBlue {
  back_default: string;
  back_gray: string;
  back_transparent: string;
  front_default: string;
  front_gray: string;
  front_transparent: string;
}

export interface GenerationIi {
  // eslint-disable-next-line no-use-before-define
  crystal: Crystal;
  // eslint-disable-next-line no-use-before-define
  gold: Gold;
  // eslint-disable-next-line no-use-before-define
  silver: Gold;
}

export interface Crystal {
  back_default: string;
  back_shiny: string;
  back_shiny_transparent: string;
  back_transparent: string;
  front_default: string;
  front_shiny: string;
  front_shiny_transparent: string;
  front_transparent: string;
}

export interface Gold {
  back_default: string;
  back_shiny: string;
  front_default: string;
  front_shiny: string;
  front_transparent?: string;
}

export interface GenerationIii {
  // eslint-disable-next-line no-use-before-define
  emerald: Emerald;
  'firered-leafgreen': Gold;
  'ruby-sapphire': Gold;
}

export interface Emerald {
  front_default: string;
  front_shiny: string;
}

export interface Home {
  front_default: string;
  front_female: null;
  front_shiny: string;
  front_shiny_female: null;
}

export interface GenerationVii {
  // eslint-disable-next-line no-use-before-define
  icons: DreamWorld;
  'ultra-sun-ultra-moon': Home;
}

export interface DreamWorld {
  front_default: string;
  front_female: null;
}

export interface GenerationViii {
  icons: DreamWorld;
}

export interface Other {
  dream_world: DreamWorld;
  home: Home;
  // eslint-disable-next-line no-use-before-define
  'official-artwork': OfficialArtwork;
}

export interface OfficialArtwork {
  front_default: string;
}

export interface Stat {
  base_stat: number;
  effort: number;
  stat: Species;
}

export interface Type {
  slot: number;
  type: Species;
}
